spring:
  application:
    name: resilience-app
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/resilience4j}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:postgrespw}
    hikari:
      minimumIdle: ${HIKARI_POOL_MINIMUM_IDLE:1}
      maximumPoolSize: ${HIKARI_POOL_MAXIMUM_POOL_SIZE:2}
      idleTimeout: ${HIKARI_POOL_IDLE_TIMEOUT:60000}
      maxLifetime: 2000000
      connectionTimeout: ${HIKARI_CONNECTION_TIMEOUT:60000}
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non-contextual-creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

management:
  server:
    port: 8081
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'