resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        failure-rate-threshold: 50
        minimum-number-of-calls: 20
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 2
        sliding-window-size: 20
        sliding-window-type: count_based
        slow-call-duration-threshold: 10s
        slow-call-rate-threshold: 50
    instances:
      externalService:
        base-config: default
      importantService:
        base-config: default
        wait-duration-in-open-state: 30s
        failure-rate-threshold: 75